apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: facturation-client
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 30002
  type: NodePort
  