apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring  # Le namespace correct de Prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'facturation-server'
        static_configs:
          - targets: ['server-service:3000']  # Remplacez par le nom de votre service
        metrics_path: '/metrics'
        scheme: 'http'
