apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  annotations:  # Moved annotations here under metadata
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: facturation-server
  template:
    metadata:
      labels:
        app: facturation-server
    spec:
      containers:
      - name: facturation-server
        image: oumaimarouis/facturation-server:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: app-configmap
